apiVersion: v2
name: wordpress
description: WordPress Helm chart
type: application
version: 0.1.0
appVersion: "6.7"

dependencies:
  - name: mariadb
    version: "20.2.1"
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
