replicaCount: 2

image:
  repository: wordpress-devops
  tag: local
  pullPolicy: Never

standaloneMariadb:
  enabled: true
  image: mariadb:11
  rootPassword: local-root
  password: local-wp

ingress:
  host: wordpress.local

persistence:
  storageClass: local-rwx
  accessMode: ReadWriteMany

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

env:
  WP_ENV: local
  WP_DEBUG: "true"

podDisruptionBudget:
  enabled: true
  minAvailable: 1