apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  WP_ENV: {{ .Values.env.WP_ENV | quote }}
  WORDPRESS_DEBUG: {{ if eq (.Values.env.WP_DEBUG | toString) "true" }}"1"{{ else }}""{{ end }}
