apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  WP_ENV: {{ .Values.env.WP_ENV | quote }}
  WP_DEBUG: {{ .Values.env.WP_DEBUG | quote }}
