apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ include "wordpress.dbPassword" . | quote }}
